# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restless < Formula
  desc "Terminal-native HTTP client using .http files with TUI and headless CLI"
  homepage "https://github.com/shahadulhaider/restless"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.1.0/restless_0.1.0_darwin_amd64.tar.gz"
      sha256 "7800766719575b47ae861700e6c8350e820a6135b0bfa348a776b7cd2f63457b"

      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.1.0/restless_0.1.0_darwin_arm64.tar.gz"
      sha256 "86bc67b1d43c8299a9d9f3f7eef64683e97f939b77700faa2454047ccd8ccb29"

      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.1.0/restless_0.1.0_linux_amd64.tar.gz"
      sha256 "c8f8c0f43f4a90d164cb6023f7bf2434ae4da67b7af8e1008c17d86f123d47cf"
      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.1.0/restless_0.1.0_linux_arm64.tar.gz"
      sha256 "2eb0531389de150020c31a417f39a0f0df692da3f295d4367522b2ea1ae46d61"
      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  test do
    system "#{bin}/restless", "version"
  end
end
