# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envdiff < Formula
  desc "Compare, validate, and sync .env files across environments"
  homepage "https://github.com/shahadulhaider/envdiff"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahadulhaider/envdiff/releases/download/v1.0.0/envdiff_1.0.0_darwin_amd64.tar.gz"
      sha256 "b5425384089a57c84e9f022c0aeb6ebbffb07c2b70784d6f9e56ddaf46896f17"

      define_method(:install) do
        bin.install "envdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahadulhaider/envdiff/releases/download/v1.0.0/envdiff_1.0.0_darwin_arm64.tar.gz"
      sha256 "9bac91e09d3b5c66039da1a68081cac0ab6af502ee51cb81377914695f843eb8"

      define_method(:install) do
        bin.install "envdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/envdiff/releases/download/v1.0.0/envdiff_1.0.0_linux_amd64.tar.gz"
      sha256 "dbcdb98eb47ce4fca89bb5da438c7c2a4db78718c11393d68979370d3a01e105"
      define_method(:install) do
        bin.install "envdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/envdiff/releases/download/v1.0.0/envdiff_1.0.0_linux_arm64.tar.gz"
      sha256 "cc9a2a164e4e8c45f7c62ef77c5989d832f8f5f3563cb034cb7bd119d59173fc"
      define_method(:install) do
        bin.install "envdiff"
      end
    end
  end

  test do
    system "#{bin}/envdiff", "--version"
  end
end
