# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ports < Formula
  desc "A fast, keyboard-driven TUI for exploring listening ports on macOS and Linux"
  homepage "https://github.com/shahadulhaider/ports"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_darwin_amd64.tar.gz"
      sha256 "e2541197e25d77dc109ab6a2a1e6b450199e428e3959586ed7109003388d5eeb"

      define_method(:install) do
        bin.install "ports"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_darwin_arm64.tar.gz"
      sha256 "96f7dbbffce976aa1511f7056a3bf51c55fa49db78260efd82df45f82c4bce29"

      define_method(:install) do
        bin.install "ports"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_linux_amd64.tar.gz"
      sha256 "96b1387430e45fa2905484aa366869128c3242122d38674c7b26d2b6002c7a03"
      define_method(:install) do
        bin.install "ports"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_linux_arm64.tar.gz"
      sha256 "13e4ff787cdd04808fdffb867136ce42b333c6ba095ec81207e5337b8dba552f"
      define_method(:install) do
        bin.install "ports"
      end
    end
  end

  test do
    system "#{bin}/ports", "--version"
  end
end
