# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ports < Formula
  desc "A fast, keyboard-driven TUI for exploring listening ports on macOS and Linux"
  homepage "https://github.com/shahadulhaider/ports"
  version "1.0.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_darwin_amd64.tar.gz"
      sha256 "cdfe939c7d6aa7906e379c6c9f78fc70fabb07e35c6a6456cbfe7022cf841439"

      define_method(:install) do
        bin.install "ports"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_darwin_arm64.tar.gz"
      sha256 "9d3ec3d2a6a4ac86c527f33d071c0afc37c45cc16fbd9615b37edd2def50b95e"

      define_method(:install) do
        bin.install "ports"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_linux_amd64.tar.gz"
      sha256 "56bbe932a704bc53892309f5f49bf26e022ff16ad5bec1bcbc01ff2ebcf156c3"
      define_method(:install) do
        bin.install "ports"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/ports/releases/download/v1.0.0/ports_1.0.0_linux_arm64.tar.gz"
      sha256 "fcfb2ac784afbe2ec67d4484bd23115d327bb153d3a448a0f13933777a418676"
      define_method(:install) do
        bin.install "ports"
      end
    end
  end

  test do
    system "#{bin}/ports", "--version"
  end
end
