# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restless < Formula
  desc "Terminal-native HTTP client using .http files with TUI and headless CLI"
  homepage "https://github.com/shahadulhaider/restless"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.3.0/restless_0.3.0_darwin_amd64.tar.gz"
      sha256 "6467673cba693b85ecbe959d02d2c0df37748f14f4bf68925e951b7ddc122ff7"

      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.3.0/restless_0.3.0_darwin_arm64.tar.gz"
      sha256 "157c2b879c5e02e01e748482f9b904d9a301b453f29d593781622b0851f26785"

      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.3.0/restless_0.3.0_linux_amd64.tar.gz"
      sha256 "4e9283a991ad59078f817310a1c74a5a3ca80fbfd0fb894a3cb2e616b2400511"
      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.3.0/restless_0.3.0_linux_arm64.tar.gz"
      sha256 "c743acace6beeba4e6e79d734cdb62625dfe6a31d865713245fed9cbbdd3bd63"
      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  test do
    system "#{bin}/restless", "version"
  end
end
