# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restless < Formula
  desc "Terminal-native HTTP client using .http files with TUI and headless CLI"
  homepage "https://github.com/shahadulhaider/restless"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.9.4/restless_0.9.4_darwin_amd64.tar.gz"
      sha256 "5f88fac3f4403fabf2275b4eed7e889723f565a7f802dcde70add788c8afa00c"

      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.9.4/restless_0.9.4_darwin_arm64.tar.gz"
      sha256 "8e16ef4031a2a18c5f9cf2402e8a8c1c22a6509c296ab8685bb2f7d44e531e28"

      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.9.4/restless_0.9.4_linux_amd64.tar.gz"
      sha256 "4b988961e2058f177a7e1c2c629aa7295e0f4d748c777f57e8806b7f52544a2d"
      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.9.4/restless_0.9.4_linux_arm64.tar.gz"
      sha256 "309391c51ac7f4ab6ca1f3735a24fd7d4690a1183d59edcc8ff9515996282c50"
      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  test do
    system "#{bin}/restless", "version"
  end
end
