# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Restless < Formula
  desc "Terminal-native HTTP client using .http files with TUI and headless CLI"
  homepage "https://github.com/shahadulhaider/restless"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.5.1/restless_0.5.1_darwin_amd64.tar.gz"
      sha256 "4925085bce7810e7fe1c69028b65c3296a200f99f75153579576c2816f61c162"

      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.5.1/restless_0.5.1_darwin_arm64.tar.gz"
      sha256 "5874f23d1119f17d22aa9356bb22e2358826996ae998517f85c5e26b87d2dba9"

      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.5.1/restless_0.5.1_linux_amd64.tar.gz"
      sha256 "9d27d50714914c86e9b9e4a1c76b3dfabe533e6ccd7b2f658a9680c587797306"
      define_method(:install) do
        bin.install "restless"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shahadulhaider/restless/releases/download/v0.5.1/restless_0.5.1_linux_arm64.tar.gz"
      sha256 "8dfed48e580cf74928e8c50e0d4351a708483735cc673b5b49c39d86f14c3306"
      define_method(:install) do
        bin.install "restless"
      end
    end
  end

  test do
    system "#{bin}/restless", "version"
  end
end
